# Project: Sample_for_R1_2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o test.o 
LINKOBJ  = main.o test.o
LIBS     = -L"../cft4cpp-core/MinGW64/lib" -L"../cft4cpp-core/program files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"../cft4cpp-core/program files/Dev-Cpp/MinGW64/include" -I"../cft4cpp-core/program files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"../cft4cpp-core/program files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"../cft4cpp-core/program files/Dev-Cpp/MinGW64/include" -I"../cft4cpp-core/program files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"../cft4cpp-core/program files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"../cft4cpp-core/program files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Sample_for_R1_2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

test.o: test.cpp
	$(CPP) -c test.cpp -o test.o $(CXXFLAGS)

FnCall2.o: FnCall2.cpp
	$(CPP) -c FnCall2.cpp -o FnCall2.o $(CXXFLAGS)



